# Generated by Django 4.2.4 on 2023-09-15 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DateHeroes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Hero", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Heroes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HeroID", models.IntegerField(default=0)),
                (
                    "CodeName",
                    models.CharField(default="npc_dota_hero_base", max_length=33),
                ),
                ("Name", models.CharField(default="Hero", max_length=19)),
                ("Role", models.CharField(default="Role", max_length=60)),
                ("Rolelevels", models.CharField(default="1", max_length=16)),
                ("Team", models.CharField(default="Radiant", max_length=7)),
                ("AttackType", models.CharField(default="Melee", max_length=50)),
                ("SimilarHeroesID", models.CharField(default="0,0,0", max_length=11)),
                (
                    "AttributePrimary",
                    models.CharField(default="DOTA_ATTRIBUTE_ALL", max_length=24),
                ),
                ("LastHitChallengeRivalID", models.IntegerField(default=0)),
                ("NameAliases", models.CharField(default="Hero", max_length=50)),
                ("Adjectives", models.CharField(default="{}", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classic_isguessed", models.BooleanField()),
                ("classic_attempts", models.IntegerField()),
                ("ranked_isguessed", models.BooleanField()),
                ("ranked_attempts", models.IntegerField()),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dateheroes"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
